### ISSUE TITLE
No SD Codes Found, then System Crash.

### ISSUE THREAD

**Issue by ghost** [iGlitch/GeckoOS#1]
I'll keep this brief. Basically, I set up codes to be used with SSBB which work perfectly on the regular Gecko OS. (which is also the latest version, 1.9.3.1) But when I try to use this version of Gecko OS, not only does it not detect the codes, it also crashes giving an unusual error: Exception (Program) Occurred, instead of the more common: Exception (DSI) Occurred.
For any extra info that might be needed, I am currently using the vWii and I'm also using a gameconfig.txt for Brawl. Again, this issue does not occur on the official Gecko OS release.
Any idea what the main issue may be?
Thanks in advance. - GABO1423
![20200312_170601](https://user-images.githubusercontent.com/35014183/76566826-f90b9280-6483-11ea-8de8-bfa9177f315d.jpg)

**Comment by lemaximedu66** [comment]
yeah, looks like it also does it for dolphin (even tho there is already an option to use gecko codes)

<img width="1120" height="750" alt="Image" src="https://github.com/user-attachments/assets/748c390f-4bd6-403f-b3c8-5a9a262610c8" />

<img width="3806" height="2302" alt="Image" src="https://github.com/user-attachments/assets/474bf966-a715-458b-9a83-914d0613844a" />
